language: node_js
node_js:
  - 10
scripts:
  - npm install codecov -g
  - npm run lint
  - npm run build
  - npm run test:coverage:json
after_success:
  - npx gulp -f ./node_modules/base-project-config/gulpfile-coverage.js
  - codecov
